config/routes.rb
Rails.application.routes.draw do

  resources :buses

  resources :routes

  resources :stops

  devise_for :users
  unauthenticated do
    root to: 'welcome#index'
  end

  authenticated :user do
    root to: 'users#index', as: :user_root
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      
      resources :stops, only: [:index] do
        resources :buses, only: [:index]
      end

      resources :buses, only: [:show]
      resources :users, only: [:index, :update]
      
      patch '/balance_reloads' => 'balance_reloads#create' , :as => 'create_balance_reloads'
      patch '/ticket_payments' => 'ticket_payments#create' , :as => 'create_ticket_payments'
      
      patch '/buses/position' => 'buses#update_position', :as => 'buses_update_position'
    end
  end
end

app/models/stop.rb
class Stop < ActiveRecord::Base

  validates :name, :latitude, :longitude,  presence: true
  
  belongs_to :route
  
end

app/controllers/api/v1/stops_controller.rb
class Api::V1::StopsController < ApplicationController

  def index
    delta=0.005
    
    min_longitude=params[:longitude].to_f-delta
    max_longitude=params[:longitude].to_f+delta
    
    min_latitude=params[:latitude].to_f-delta
    max_latitude=params[:latitude].to_f+delta
    
    stops=Stop.where(latitude: (min_latitude .. max_latitude), longitude: (min_longitude .. max_longitude))
    render json: stops, status: :ok
  end

end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]

  # GET /stops
  # GET /stops.json
  def index
    @stops = Stop.all
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
    @routes = Route.all
  end

  # GET /stops/1/edit
  def edit
    @routes = Route.all
  end

  # POST /stops
  # POST /stops.json
  def create
    
    @stop = Stop.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url, notice: 'Stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_params
      params.require(:stop).permit(:name, :longitude, :latitude, :route_id)
    end
end

app/helpers/api/v1/stops_helper.rb
module Api::V1::StopsHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.haml
= form_for @stop, html: { class: "form form-horizontal stop" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@stop[:name])
  .form-group
    = f.label :latitude, class: 'control-label'
    .controls
      = f.text_field :latitude, class: 'form-control', required: true
    = error_span(@stop[:latitude])
  .form-group
    = f.label :longitude, class: 'control-label'
    .controls
      = f.text_field :longitude, class: 'form-control', required: true
    = error_span(@stop[:longitude])
  .form-group
    = f.label :route_id, class: 'control-label'
    .controls
      = collection_select :stop, :route_id, @routes, :id, :name
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), stops_path, :class => 'btn btn-default'

app/views/stops/edit.html.haml
- model_class = Stop
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stops/index.html.haml
- model_class = Stop
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:latitude)
      %th= model_class.human_attribute_name(:longitude)
      %th= model_class.human_attribute_name(:route)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @stops.each do |stop|
      %tr
        %td= link_to stop.id, stop_path(stop)
        %td= stop.name
        %td= stop.latitude
        %td= stop.longitude
        %td= stop.route.name
        %td= stop.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_stop_path(stop), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), stop_path(stop), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_stop_path, :class => 'btn btn-primary'

app/views/stops/new.html.haml
- model_class = Stop
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stops/show.html.haml
- model_class = Stop
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @stop.name
%p
  %strong= model_class.human_attribute_name(:latitude) + ':'
  %br
  = @stop.latitude
%p
  %strong= model_class.human_attribute_name(:longitude) + ':'
  %br
  = @stop.longitude


= link_to t('.back', :default => t("helpers.links.back")), stops_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_stop_path(@stop), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), stop_path(@stop), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'