config/routes.rb
Rails.application.routes.draw do

  resources :buses

  resources :routes

  resources :stops

  devise_for :users
  unauthenticated do
    root to: 'welcome#index'
  end

  authenticated :user do
    root to: 'users#index', as: :user_root
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      
      resources :stops, only: [:index] do
        resources :buses, only: [:index]
      end

      resources :buses, only: [:show]
      resources :users, only: [:index, :update]
      
      patch '/balance_reloads' => 'balance_reloads#create' , :as => 'create_balance_reloads'
      patch '/ticket_payments' => 'ticket_payments#create' , :as => 'create_ticket_payments'
      
      patch '/buses/position' => 'buses#update_position', :as => 'buses_update_position'
    end
  end
end

app/controllers/api/v1/buses_controller.rb
class Api::V1::BusesController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def update_position
    bus=Bus.where(bid: bid=bus_params[:bid]).first
    if bus.update(bus_params)
      if bleus_action
        if bleus_action == 'Check-In'
          bus.increase_passengers
        elsif bleus_action == 'Check-Out'
          bus.decrease_passengers
        end
        bus.save
      end
    
      render json: bus, status: :ok
    else
      render json: episode.errors, status: 422
    end

    
  end


  def index
    delta=0.005
    stop=Stop.find(params[:stop_id])
    
    min_longitude=stop.longitude-delta
    max_longitude=stop.longitude+delta
    
    min_latitude=stop.latitude-delta
    max_latitude=stop.latitude+delta
    stop=Stop.find(params[:stop_id])
    buses=Bus.where(route: stop.route, latitude: (min_latitude .. max_latitude), longitude: (min_longitude .. max_longitude))    
    render json: buses, status: :ok
  end

  def show
    bus=Bus.where(:bid => params[:id]).first
    render json: bus, status: :ok
  end

  private
  def bus_params
    params.require(:bus).permit( :bid, :longitude, :latitude)
  end
  
  def bleus_action
    request.headers['Bleus-Action']
  end
  
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]
  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
    @routes = Route.all
  end

  # GET /buses/1/edit
  def edit
    @routes = Route.all
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bus
    @bus = Bus.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bus_params
    params.require(:bus).permit(:name, :bid, :route_id)
  end
end

app/helpers/api/v1/buses_helper.rb
module Api::V1::BusesHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_form.html.haml
= form_for @bus, html: { class: "form form-horizontal bus" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@bus[:name])
  .form-group
    = f.label :bid, class: 'control-label'
    .controls
      = f.text_field :bid, class: 'form-control', required: true
    = error_span(@bus[:bid])
  .form-group
    = f.label :route_id, class: 'control-label'
    .controls
      = collection_select :bus, :route_id, @routes, :id, :name
    = error_span(@bus[:route_id])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), buses_path, :class => 'btn btn-default'

app/views/buses/edit.html.haml
- model_class = Bus
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/buses/index.html.haml
- model_class = Bus
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:bid)
      %th= model_class.human_attribute_name(:latitude)
      %th= model_class.human_attribute_name(:longitude)
      %th= model_class.human_attribute_name(:passengers)
      %th= model_class.human_attribute_name(:route_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @buses.each do |bus|
      %tr
        %td= link_to bus.id, bus_path(bus)
        %td= bus.name
        %td= bus.bid
        %td= bus.latitude
        %td= bus.longitude
        %td= bus.passengers
        %td= bus.route.name
        %td= bus.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_bus_path(bus), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), bus_path(bus), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_bus_path, :class => 'btn btn-primary'

app/views/buses/new.html.haml
- model_class = Bus
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/buses/show.html.haml
- model_class = Bus
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @bus.name
%p
  %strong= model_class.human_attribute_name(:bid) + ':'
  %br
  = @bus.bid
%p
  %strong= model_class.human_attribute_name(:route_id) + ':'
  %br
  = @bus.route_id


= link_to t('.back', :default => t("helpers.links.back")), buses_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_bus_path(@bus), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), bus_path(@bus), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'